# Travis Badge Markdown (add to README.md): [![Build Status](https://secure.travis-ci.org/x62en/meteor-livetoken-base.png?branch=master)](https://travis-ci.org/x62en/meteor-livetoken-base)
sudo: required
language: node_js
node_js:
  - "0.10"

install:
  - "curl https://install.meteor.com | /bin/sh"
